name: Build and deploy a production container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: backend22  # Nombre de tu aplicación web en Azure
  IMAGE_NAME: esproject         # Nombre base de la imagen Docker
  TAG_NAME: build-tag-1         # Etiqueta personalizada de la imagen Docker

on:
  push:
    branches: [ "main", "develop" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        working-directory: ./backend
        run: |
          echo "Logging in to Azure Container Registry"
          docker login contreg22.azurecr.io -u contreg22 -p ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}

      - name: Build Docker image
        working-directory: ./backend
        run: |
          echo "Building Docker image"
          docker build -t contreg22.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }} .

      - name: Push Docker image to Azure Container Registry
        working-directory: ./backend
        run: |
          echo "Pushing Docker image to Azure Container Registry"
          docker push contreg22.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'

    steps:
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          echo "Deploying to Azure Web App"
          az webapp config container set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group backend22_group \
            --docker-custom-image-name contreg22.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }} \
            --docker-registry-server-url https://contreg22.azurecr.io \
            --docker-registry-server-user contreg22 \
            --docker-registry-server-password ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}

      - name: Restart Azure Web App
        run: |
          echo "Restarting Azure Web App"
          az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group backend22_group

