name: Frontend Tests

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check out the repository
        uses: actions/checkout@v4

      # Set up Docker Buildx (used to enable advanced features in Docker)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

       # Set up backend Docker container
      - name: Build backend Docker
        run: |
          echo "HOST=${{ secrets.HOST }}" > .env
          echo "USERDB=${{ secrets.USERDB }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "DATABASE=${{ secrets.DATABASE }}" >> .env
          echo "PROJECT_NAME=ReadHub" >> .env
          echo "FIRST_SUPERUSER=admin" >> .env
          echo "FIRST_SUPERUSER_PASSWORD=admin123" >> .env
          echo "BACKEND_CORS_ORIGINS=http://localhost:8080" >> .env

          docker build -t backend -f backend/Dockerfile backend

          docker run -p 8000:80 --env-file .env backend &

      # Build frontend Docker container
      - name: Build frontend Docker
        run: |
          docker build -t frontend -f frontend/Dockerfile frontend
          docker run -p 8080:8080 frontend &

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: |
          cd frontend
          npm install

      # Test frontend connectivity
      - name: Test frontend connectivity
        run: curl -v http://localhost:8080/login

      # Test backend connectivity
      - name: Test backend connectivity
        run: |
          # Verificar que la API responde
          curl -X 'GET' \
          'http://localhost:8000/api/v1/users/by-id/20' \
          -H 'accept: application/json' \
          -v


      # Run Selenium tests with Google Chrome
      - name: Run Selenium tests
        env:
          HOST: ${{ secrets.HOST }}
          USERDB: ${{ secrets.USERDB }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DATABASE: ${{ secrets.DATABASE }}
          PROJECT_NAME: "ReadHub"
          FIRST_SUPERUSER: "admin"
          FIRST_SUPERUSER_PASSWORD: "admin123"
          VUE_APP_ENCODING_SECRET_KEY: ${{ secrets.VUE_APP_ENCODING_SECRET_KEY }}
        run: |
          cd frontend
          npm run test